# Generated by Django 3.2.17 on 2023-05-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0024_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivements',
            name='year',
            field=models.CharField(choices=[('2023-24', '2023-24'), ('2022-23', '2022-23'), ('2021-22', '2021-22'), ('2020-21', '2020-21')], default='2023-24', max_length=200),
        ),
        migrations.AddField(
            model_name='associationteammembers',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
